export const wavesMap = [
    [
        {type: 'solder', count: 5, duration: 10, way: 0},
        {type: 'solder', count: 5, duration: 10, way: 1},
        {type: 'solder', count: 5, duration: 10, way: 0},
        {type: 'solder', count: 5, duration: 10, way: 1},
    ],
    [
        {type: 'solder', count: 10, duration: 10, way: 0},
        {type: 'solder', count: 10, duration: 10, way: 1},
        {type: 'solder-laser', count: 2, duration: 10, way: 0},
        {type: 'solder-laser', count: 2, duration: 10, way: 1},
        {type: 'tank', count: 1, duration: 10, way: 0},
    ],
    [
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'tank', count: 2, duration: 10, way: 0},
        {type: 'tank', count: 2, duration: 10, way: 1},
    ],
    [
        {type: 'laser-tank', count: 2, duration: 10, way: 0},
        {type: 'laser-tank', count: 2, duration: 10, way: 1},
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'solder-laser', count: 8, duration: 10, way: 0},
        {type: 'solder-laser', count: 8, duration: 10, way: 1},
    ],
    [
        {type: 'solder', count: 25, duration: 7, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
    ],
    [
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
    ],
    [
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
    ],
    [
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
    ],
    [
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'solder', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 4, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
    ],
    [
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'laser-tank', count: 4, duration: 10, way: 1},
        {type: 'laser-tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'solder', count: 16, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 16, duration: 10, way: 1},
        {type: 'solder', count: 25, duration: 10, way: 0},
        {type: 'tank', count: 4, duration: 10, way: 1},
        {type: 'solder-laser', count: 16, duration: 10, way: 0},
        {type: 'solder', count: 25, duration: 10, way: 1},
        {type: 'tank', count: 4, duration: 10, way: 0},
        {type: 'solder-laser', count: 4, duration: 10, way: 1},
        {type: 'solder', count: 25, duration: 10, way: 0},
    ],

]
